### ISSUE TITLE
roles reversed

### ISSUE THREAD

**Issue by aquaticcalf** [GDG-Oncampus-VIIT-24/GDGC-Website#22]
## in team component 
![screenshot_19122024_184413](https://github.com/user-attachments/assets/0b69477e-98cf-4329-88c9-57d66fa202d5)

github < - > linkedin

@MGuruNikhil

**Comment by aquaticcalf** [comment]
thank you for the quick response, you are faster than :rocket: 

@MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil 

@MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil 

@MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil 

@MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil 

@MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil 

@MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil 

@MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil 

@MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil 

@MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil 

@MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil 

@MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil 

@MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil 

@MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil 

@MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil 

@MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil 

@MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil 

@MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil 

@MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil @MGuruNikhil

**Comment by jagadeesh-debug** [comment]
mind blowing issuse mentioed by @aquaticcalf
